version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/xyborg
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    volumes:
      - data:/data/db
  redis:
    image: redis
volumes:
  data:
